### ISSUE TITLE
Permission denied: '/home/tribler/.Tribler/logs'

### ISSUE THREAD

**Issue by Snake883** [Tribler/docker-tribler-prod#2]
When I run the command, I get error:

```
$ docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/snd -v $HOME/.Tribler:/home/tribler/.Tribler -v $HOME/Downloads:/home/tribler/TriblerDownloads --name tribler tribler/docker-tribler-prod
Traceback (most recent call last):
  File "run_tribler.py", line 102, in <module>
    enable_fault_handler()
  File "/home/tribler/tribler/check_os.py", line 234, in enable_fault_handler
    os.makedirs(log_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/tribler/.Tribler/logs'
```

**Comment by Snake883** [comment]
I believe I have found the problem.  Running the above command will create a .Tribler folder with root as the owner.  To workaround the problem, I created the .Tribler problem as my user.
