### ISSUE TITLE
Exception on launching tribler

### ISSUE THREAD

**Issue by Dikakus** [Tribler/docker-tribler-prod#5]
Hi. I'm quite newby, so sorry if I say something worong.

I built the docker version of tribler with some tricks to work in a raspberry pi 4.

When I launched the container, tribler throws this exception:

```
[PID:22] 2021-09-27 16:33:37,836 - ERROR <error_handler:37> ErrorHandler.gui_error(): tribler_gui.utilities.CreationTraceback:
  File "/home/tribler/tribler/src/run_tribler.py", line 213, in <module>
    sys.exit(app.exec_())
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 151, in connect
    connect(self.reply.error, lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 151, in <lambda>
    connect(self.reply.error, lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))
  File "/home/tribler/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 87, in on_error
    raise CoreConnectTimeoutError("Could not connect with the Tribler Core within 60 seconds")
tribler_gui.event_request_manager.CoreConnectTimeoutError: Could not connect with the Tribler Core within 60 seconds
[PID:44] 2021-09-27 16:32:41,105 - ERROR <session:240> Session.unhandled_error_observer(): Unhandled exception occurred! [Errno 99] error while attempting to bind on address ('::1', 52194, 0, 0): cannot assign requested address
--LONG TEXT--
Traceback (most recent call last):
  File "/home/tribler/tribler/src/run_tribler.py", line 98, in start_tribler
    await session.start()
  File "/home/tribler/tribler/src/tribler-core/tribler_core/session.py", line 287, in start
    await self.api_manager.start()
  File "/home/tribler/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 123, in start
    await self.site.start()
  File "/home/tribler/.local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 52194, 0, 0): cannot assign requested address

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': OSError(99, "error while attempting to bind on address ('::1', 52194, 0, 0): cannot assign requested address"), 'future': <Task finished name='Task-1' coro=<start_tribler_core.<locals>.start_tribler() done, defined at /home/tribler/tribler/src/run_tribler.py:62> exception=OSError(99, "error while attempting to bind on address ('::1', 52194, 0, 0): cannot assign requested address")>}

[PID:22] 2021-09-27 16:33:37,896 - INFO - SentryReporter(286) - Event from exception: Could not connect with the Tribler Core within 60 seconds

```

Any idea? Thank you.

**Comment by mitchellolsthoorn** [comment]
Hi @Dikakus,

The most important thing that jumps out at me is:
`error while attempting to bind on address ('::1', 52194, 0, 0): cannot assign requested address`

This could either mean that:
- There is no permission to bind to the address (unlikely in Docker)
- There is already something listening on that port (also unlikely in Docker)
- It does not recognize the binding address: Maybe RPIs don't support the ipv6 local address (::1). Changing this to 127.0.0.1 could possibly work.

**Comment by Dikakus** [comment]
Hi @mitchellolsthoorn, 

Thank you for your reply. I've been doing a bit of research from your clue. It was also strange to me that the address appeared in ipv6 format.

I don't know how change it to 127.0.0.1, but in the end, it worked commenting out the ipv6 addresses that were defined in /etc/host of the host machine. I have no idea how they got there.

For what it's worth, these are some changes I've had to make to the Docker file:

Modify VERSION argument:

`ARG VERSION=v7.10.0`

Add a line 

`RUN pip3 install faker sentry_sdk yappi`

after install pyipv8 requirements.

I don't know why but I had a library error on launching tribler that I solved with:

`CMD ["/bin/sh", "-c", "LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 /home/tribler/tribler/src/tribler.sh"]`

**Comment by mitchellolsthoorn** [comment]
Great that you could get it to work.

We have never tested the Docker container on ARM, so it could be that the linking does not work properly on that platform. Thank you for providing instructions for other people that might want to run this configuration.
